### ISSUE TITLE
Distribute a transpiled version on npm registry

### ISSUE THREAD

**Issue by matbour** [kyscott18/allegedly#1]
Currently the package is made with bun and only exports an index.js. To be usable on other runtimes like Node.js, the package need to transpiled to JS.

**Comment by kyscott18** [comment]
Thanks for opening! I haven't done a real release yet, just an alpha release to make sure I reserved the namespace. I will make sure to do this once more of Solidity is supported.

**Comment by matbour** [comment]
Got it, thanks a lot for clarification!
